version: "3"
services:
  app:
    container_name: clean_arch_app
    build: .
    ports:
      - "5011:5011"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - clean_arch_network
    depends_on:
      - db-app

  db-app:
    container_name: clean_arch_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_User: root
      MYSQL_DATABASE: clean_arch_db
    ports:
      - "8050:3306"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - clean_arch_network

volumes:
  api:
  database_postgres:

networks:
  clean_arch_network:
    driver: bridge